---
abstract: 'Perl interface to Notify My Android web API'
author:
  - 'Steve Huff <shuff@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-NotifyMyAndroid
provides:
  WebService::NotifyMyAndroid:
    file: lib/WebService/NotifyMyAndroid.pm
    version: v0.0.3
requires:
  Carp: 0
  Data::Printer: 0
  FindBin::libs: 0
  LWP::Protocol::https: 0
  Params::Validate: 0
  Readonly: 0
  Regexp::Common: 0
  WebService::Simple: 0
  XML::Simple: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.3
